Heptagram-Project/website

index.html
Added some meta tags to improve the ranking of the website
=> Worked on the SEO of the heptagram.xyz

.htaccess, invite.html
Fairly simple, no explanation needed. :)
=> Added /invite redirect

README.md, css/style-heptagramdevs.css, css/style.css, heptagram-devs.html, index.html
I worked on the :
--> Documentation : Improved the README.md
--> Website : Enhanced the coming soon page by changing the background color of the header and footer + adding the Heptagram Developers page (Under Construction)
=> Improved the coming soon page and README.md

commands.html, css/style-commands.css, css/style-landingpage.css, css/style-tutorials.css, landingpage.html, tutorials.html
Designed and coded these pages
=> Website Pages : Commands, Tutorials and Landing Page

.htaccess, commands.html, css/style-commands.css, css/style-landingpage.css, css/style-tutorials.css, heptagram-devs.html, index.html, invite.html, landingpage.html, tutorials.html
Deleted the Discord Login Button
Renamed Features to Home
Edited some Meta Tags
=> Website Dev : Small Changes

css/style-landingpage.css, landingpage.html
I finished working on the landingpage.html
It is ready now !
=> Website Pages : Finished the Home Page

404.html, coming-soon.html, commands.html
The text in 404.html and coming-soon.html is visible now !
=> Website Dev : Fixed Accessibility Issues

main.js
=> Fixed Tabs Bug (commands.html)

commands.html, css/style-commands.css, css/style-heptagramdevs.css, css/style-landingpage.css, css/style-tutorials.css, heptagram-devs.html, landingpage.html, tutorials.html
All the pages has now the Heptagram Footer !
=> Website Components : Footer added to all pages

index.html
Things added/changed:
- Capitalize the `Discord` word.
=> Capitalize the `Discord` word

README.md
Things added/changed:
- Capitalize `h` in the `GitHub` word in the `README.md` file.
=> Capitalize `h` in the `GitHub` word in the `README.md` file

index.html
- Update Discord text (check the Git diff for changes).
=> feat: Update Discord text (check the Git diff for changes)

index.html
=> fix: Re-add favicon again

commands.html, heptagram-devs.html, index.html, privacy-policy.html, terms-of-service.html
I created and styled the privacy policy page (privacy-policy.html) and terms of service page (terms-of-service.html)
The styling is the same as the other pages i designed and coded
Closes #32
=> Privacy Policy & Terms of Service Pages

heptagram-devs.html
- Fix avatars not showing up on developers' page.
Closes #47
=> fix: avatars not showing up on developers page

heptagram.xyz/package-lock.json, heptagram.xyz/public/index.html, heptagram.xyz/src/App.js, heptagram.xyz/src/Components/Hamburger.js, heptagram.xyz/src/Components/Header-Cmd.js, heptagram.xyz/src/Components/Header.js, heptagram.xyz/src/Pages/Error404Page.js, heptagram.xyz/src/Pages/Error500Page.js, heptagram.xyz/src/Styles/style-commands.css, heptagram.xyz/src/Styles/style-error.css, heptagram.xyz/src/Styles/styles.css, heptagram.xyz/src/pages/BotCommandsPage.js, heptagram.xyz/src/styles/style-contributors.css, heptagram.xyz/src/styles/style-legals.css
We're getting closer to finish the React Switch !
=> Created Error Pages + Fixed bugs

package.json, src/App.js, src/Pages/Error404Page.js
- Fix redirect 404.
- Rename `class` to `className`
Closes #94 
=> Fix redirect 404

src/App.js
Forgot to add `Switch` to previous PR which lead to have 404 page render on every page at the bottom.
Closes #94 
=> Fix 404 page showing at the bottom

.gitpod.yml, package-lock.json
- Run NPM commands on Gitpod start.
- This will make the website run every time you start Gitpod (it will open as "preview" mode).
#67
=> Run NPM commands on Gitpod start

public/index.html
=> fix: Add `og:locale`

package-lock.json, package.json, src/App.js, src/Components/Card.js, src/Components/Header.js, src/Pages/BotDashboardPage.js, src/Styles/styles.css
> Add "Sign in with Discord Button" on the homepage
> Add Dashboard Page (currently only accessible by going to /dashboard manually)
//TODO: Mobile Responsiveness
Progresses #92 
Did you remember to update the version number in the package.json file?
I did not update the version number, because I think that it should be changed once the entire feature is finished.
For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.
=> Add Sign In With Discord button and dashboard page

public/index.html
=> Fixed the text covering the top of the homepage

package-lock.json, src/Components/Hamburger.js, src/Styles/styles.css
Fixed the issue of discord button earlier which was not showing in mobile view.
Closes #158
Did you remember to update the version number in the package.json file?
For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.
=> Fixed the issue of discord button not showing up in mobile view
